Screen:
    MDCard: 
        size_hint: None, None
        size: 500, 500
        pos_hint: {"center_x": 0.5, "center_y":0.5}
        elevation: 5 
        orientation: 'vertical'
    
        MDLabel:
            id: welcome_label
            text: "WELCOME TO ECOWHEELS"
            font_size: 30

            halign: 'center'
            height: self.texture_size[1]

        MDTextField:
            id: user
            hint_text: "username"
            required: True
            helper_text: "Enter your username here"
            helper_text_mode: "on_focus"
            icon_right: "account"
            width: 200
            font_size: 20
            pos_hint: {"center_x": 0.5}

        MDTextField:
            id: password
            hint_text: "Password"
            required: True
            helper_text: "Enter your password here"
            helper_text_mode: "on_focus"
            icon_right: "eye-off"
            width: 200
            font_size: 20
            pos_hint: {"center_x": 0.5}
            password: True
            padding: 0.2

        MDRoundFlatButton:
            text: "LOG IN"
            font_size: 12
            pos_hint: {"center_x": 0.5}

        MDRoundFlatButton:
            text: "CLEAR"
            font_size: 12
            pos_hint: {"center_x": 0.5}
            on_press: app.clear()